### ISSUE TITLE
Book Issue - Route prerequesites example

### ISSUE THREAD

**Issue by mikejerome** [hapijs-edge/hapi-plugins.com#42]
Not sure if this is the right place for this but in the section of chapter 3 discussing route prerequsites, the code example shows two arrays for pre but I think it's supposed to be mixed with an object to demonstrate the serial/parallel difference.

**Comment by thegoleffect** [comment]
Hi Mike,

Thanks for the note!  Sorry that it isn't clear but both the variables `series` and `parallel` are objects like:

```
var series = { method: handler, assign: 'some_name' };
var parallel = { method: handler, assign: 'another_name' };

pre: [
  series,
  series,
  [
    parallel,
    parallel
  ],
  series
]
```

Everything in the outer array (in the pre: [`...`]) is going to be executed in series. So it does the first series, then the second. But when it gets to the array of `parallel`'s, those two would executed in parallel before moving on to the final series. So arrays and objects are already mixed.

It kind of makes more sense if you keep reading and finish out that section.  But, we'll discuss ways to make that a lot clearer in the next update. Thanks again for reaching out!

**Comment by mikejerome** [comment]
Ok I understand. Thanks for the reply I was confused but it's clear now.
