### ISSUE TITLE
error running code

### ISSUE THREAD

**Issue by scotthathaway** [hapijs-edge/hapi-plugins.com#45]
I bought the book and tried to install the code and run it (I am running windows).  I get the following error:  

c:\server\www\hapi-plugins.com>npm run start

> hapi-plugins.com@0.0.1 start c:\server\www\hapi-plugins.com
> node index

module.js:339
    throw err;
    ^

Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (c:\server\www\hapi-plugins.com\node_modules\mongoose\lib\drivers\node-mongodb-native\objectid.js:8:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! hapi-plugins.com@0.0.1 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hapi-plugins.com@0.0.1 start script 'node index'.
npm ERR! This is most likely a problem with the hapi-plugins.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls hapi-plugins.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\server\www\hapi-plugins.com\npm-debug.log

c:\server\www\hapi-plugins.com>

Please help.

Thanks,
Scott

**Comment by shanewwarren** [comment]
I was getting the same thing when I was trying to run the project on OSX.  It seems like the problem is specifically with the version of the mongoose package defined in the project's package.json file.

By updating the mongoose dependency to point from:

```
"mongoose": "^3.9.7"
```

to 

```
"mongoose": "4.2.8"
```

and running `npm install` solved the problem for me.
