### ISSUE TITLE
Parsing error Unexpected token when using async.

### ISSUE THREAD

**Issue by jberall** [hapijs-edge/hapi-plugins.com#47]
I am using eslint-config-hapi also
Parsing error: Unexpected token is generated from the function =>
It has something to do with the async
const create = async (request, reply, sequelizeModel,createObject) => {
code...
}

**Comment by thegoleffect** [comment]
Do your node_module version numbers line up with the old package.json here? This website was written in 2015 and there was no production ready async/await at the time.
